### ISSUE TITLE
Errors once I run "npm run gulp"

### ISSUE THREAD

**Issue by heraldia** [dockwa/openpixel#47]
It shows:
[14:24:46] Using gulpfile c:\Users\me\Dev\openpixel\gulpfile.js
[14:24:46] Starting 'default'...
[14:24:46] 'default' errored after 5.47 ms
[14:24:46] TypeError: gulp.start is not a function
    at c:\Users\me\Dev\openpixel\gulpfile.js:82:8
    at taskWrapper (c:\Users\me\Dev\openpixel\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:402:14)
    at runBound (domain.js:415:12)
    at asyncRunner (c:\Users\me\Dev\openpixel\node_modules\async-done\index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openpixel@1.0.5 gulp: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openpixel@1.0.5 gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2019-08-29T19_24_46_371Z-debug.log
--
2019-08-29T19_24_46_371Z-debug.log shows
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'gulp' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'pregulp', 'gulp', 'postgulp' ]
5 info lifecycle openpixel@1.0.5~pregulp: openpixel@1.0.5
6 info lifecycle openpixel@1.0.5~gulp: openpixel@1.0.5
7 verbose lifecycle openpixel@1.0.5~gulp: unsafe-perm in lifecycle true
8 verbose lifecycle openpixel@1.0.5~gulp: PATH: C:\Program ...
9 verbose lifecycle openpixel@1.0.5~gulp: CWD: c:\Users\me\Dev\openpixel
10 silly lifecycle openpixel@1.0.5~gulp: Args: [ '/d /s /c', 'gulp' ]
11 silly lifecycle openpixel@1.0.5~gulp: Returned: code: 1  signal: null
12 info lifecycle openpixel@1.0.5~gulp: Failed to exec gulp script
13 verbose stack Error: openpixel@1.0.5 gulp: `gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid openpixel@1.0.5
15 verbose cwd c:\Users\me\Dev\openpixel
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "gulp"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error openpixel@1.0.5 gulp: `gulp`
22 error Exit status 1
23 error Failed at the openpixel@1.0.5 gulp script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by heraldia** [comment]
Figured it out, below works.
gulp.task('default', async() => {
  //gulp.start('openpixel', 'snippet');
  gulp.task('start', gulp.series('openpixel', 'snippet'), async()=> {
  });
});
